version: '3'

networks:
  mynetwork:

services:
  api:
    build: ./flask_api
    restart: unless-stopped
    ports:
      - "8443"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork


